sudo: false
language: node_js
node_js:
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"

cache:
  directories:
    - "node_modules"
    - ~/.npm

before_install:
    - npm install -g npm@latest

jobs:
  include:
    - stage: NPM audit
      script: npm run audit-ci
      node_js: "10"